allauth/urls.py
from django.conf.urls import url, patterns, include
from django.utils import importlib

from allauth.socialaccount import providers

from . import app_settings

urlpatterns = patterns('', url('^', include('allauth.account.urls')))

if app_settings.SOCIALACCOUNT_ENABLED:
    urlpatterns += patterns('', url('^social/', 
                                    include('allauth.socialaccount.urls')))

for provider in providers.registry.get_list():
    try:
        prov_mod = importlib.import_module(provider.package + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        urlpatterns += prov_urlpatterns

schedule/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url
from django.views.generic.list import ListView
from schedule.models import Calendar
from schedule.feeds import UpcomingEventsFeed
from schedule.feeds import CalendarICalendar
from schedule.periods import Year, Month, Week, Day
from schedule.views import DeleteEventView

urlpatterns = patterns(
    '',
    # urls for Calendars
    url(r'^calendar/$',
        ListView.as_view(queryset=Calendar.objects.all(),
                         template_name='schedule/calendar_list.html'),
        name="calendar_list"),

    url(r'^calendar/year/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="year_calendar",
        kwargs={'periods': [Year], 'template_name': 'schedule/calendar_year.html'}),

    url(r'^calendar/tri_month/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="tri_month_calendar",
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_tri_month.html'}),

    url(r'^calendar/compact_month/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="compact_calendar",
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_compact_month.html'}),

    url(r'^calendar/month/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="month_calendar",
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_month.html'}),

    url(r'^calendar/week/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="week_calendar",
        kwargs={'periods': [Week], 'template_name': 'schedule/calendar_week.html'}),

    url(r'^calendar/daily/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="day_calendar",
        kwargs={'periods': [Day], 'template_name': 'schedule/calendar_day.html'}),

    url(r'^calendar/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar',
        name="calendar_home",
        ),

    # Event Urls
    url(r'^event/create/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.create_or_edit_event',
        name='calendar_create_event'),
    url(r'^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$',
        'schedule.views.create_or_edit_event',
        name='edit_event'),
    # url(r'^event/completed/(?P<event_id>\d+)/$',
    #     'schedule.views.completed_event',
    #     name='completed_event'),
    url(r'^event/(?P<event_id>\d+)/$',
        'schedule.views.event',
        name="event"),
    url(r'^event/delete/(?P<event_id>\d+)/$',
        DeleteEventView.as_view(),
        name="delete_event"),

    # urls for already persisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        'schedule.views.occurrence',
        name="occurrence"),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        'schedule.views.cancel_occurrence',
        name="cancel_occurrence"),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        'schedule.views.edit_occurrence',
        name="edit_occurrence"),

    #urls for unpersisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        'schedule.views.occurrence',
        name="occurrence_by_date"),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        'schedule.views.cancel_occurrence',
        name="cancel_occurrence_by_date"),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        'schedule.views.edit_occurrence',
        name="edit_occurrence_by_date"),

    #feed urls
    url(r'^feed/calendar/upcoming/(.*)/$', UpcomingEventsFeed(), name='upcoming_events_feed'),
    url(r'^ical/calendar/(.*)/$', CalendarICalendar(), name='calendar_ical'),
    #api urls
    url(r'^api/occurrences', 'schedule.views.api_occurrences', name='api_occurences'),

    url(r'^$', ListView.as_view(queryset=Calendar.objects.all()), name='schedule'),
)

products/models.py
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.


class Product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(null=True, blank=True)
    number_of_lessons = models.PositiveIntegerField(default=1)
    price = models.DecimalField(decimal_places=2, max_digits=100,
                                default=60.00)
    discount_price = models.DecimalField(decimal_places=2, max_digits=100,
                                         null=True, blank=True)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    update_defaults = models.BooleanField(default=False)

    def __unicode__(self):
        return self.title

    class Meta:
        unique_together = ('title', 'slug')

    def get_price(self):
        return self.price

    def get_number_of_lessons(self):
        return self.number_of_lessons

    def get_discount_price(self):
        return self.discount_price

    def get_absolute_url(self):
        return reverse("single_product", kwargs={"slug": self.slug})


class ProductImage(models.Model):
    product = models.ForeignKey(Product)
    image = models.ImageField(upload_to='products/images/', null=True,
                              blank=True)
    featured = models.BooleanField(default=False)
    thumbnail = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.product.title


class VariationManager(models.Manager):
    def all(self):
        return super(VariationManager, self).filter(active=True)

    def sizes(self):
        return self.all().filter(category='size')

    def colors(self):
        return self.all().filter(category='color')


VAR_CATEGORIES = (
        ('size', 'size'),
        ('color', 'color'),
    )


class Variation(models.Model):
    product = models.ForeignKey(Product)
    title = models.CharField(max_length=120)
    image = models.ForeignKey(ProductImage, null=True, blank=True)
    price = models.DecimalField(max_digits=100, decimal_places=2, null=True,
                                blank=True)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __unicode__(self):
        return self.title

products/views.py
from django.shortcuts import render, Http404

from .models import Product, ProductImage

# Create your views here.


def massage(request):
    return render(request, 'massage.html', {})


def products(request):
    products = Product.objects.all()
    return render(request, 'products/products.html', {'products': products})


def search(request):
    try:
        q = request.GET.get('q')
    except:
        q = None

    if q:
        products = Product.objects.filter(title__icontains=q)
        context = {
            'query': q,
            'products': products
        }
        template = 'products/results.html'
    else:
        context = {}
        template = 'products/products.html'
    return render(request, template, context)


def single(request, slug):
    try:
        product = Product.objects.get(slug=slug)
        images = ProductImage.objects.filter(product=product)
        context = {
            'product': product,
            'images': images
        }
        return render(request, 'products/single.html', context)
    except:
        raise Http404

templates/products/products.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load cycle from future %}

{% block head_title %}
	- Lessons
{% endblock %}

{% block content %}
<div class="row">
    {% for product in products %}
        <div class="col-sm-3">
			<div class="thumbnail" style="height: 390px;">
				{% if product.productimage_set.all %}
					{% for item in product.productimage_set.all %}
						{% if item.featured %}

							<div style="width: 200px; margin: 0 auto;">

							<a href="{{ product.get_absolute_url }}">
								<div class="background_img_thumb" style="height: 200px; background-image: url('{{ MEDIA_URL }}{{ item.image }}');"></div>
							</a>
							</div>

						{% endif %}
					{% endfor %}
				{% else %}
					<a href="{{ product.get_absolute_url }}">
						<div class="background_img_thumb" style="height: 200px; background-image: url('{% static "img/placeholder.svg" %}');"></div>
					</a>
				{% endif %}

				<div class="caption">
					<a href="{{ product.get_absolute_url }}"><h3>{{ product.title }}</h3></a>
					{% if product.discount_price %}
						<h5>${{ product.discount_price }}</h5>
					{% else %}
						<h5>${{ product.price }}</h5>
					{% endif %}
				    <p>{{ product.description|truncatewords:10 }}</p>
				    <p><a href="{{ product.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
				</div>
			</div>
        </div>

        {% cycle "" "" "" "" "" "<br/>" %}
    {% endfor %}
{% endblock content %}

templates/products/results.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head_title %}
	- Search Results
{% endblock %}

{% block content %}
	<h1>Searched for: {{ query }}</h1>

	<table class="table">
		<thead>
		</thead>

		<tbody>
			{% for product in products %}
			<tr>
				<td style="width: 160px; height: 160px;">
					{% if product.productimage_set.all %}

						{% for item in product.productimage_set.all %}
							{% if item.featured %}
								<a href="{{ product.get_absolute_url }}">
									<div class="background_img_thumb" style="height: 160px; background-image: url('{{ MEDIA_URL }}{{ item.image }}');"></div>
								</a>
							{% endif %}
						{% endfor %}

					{% else %}
						<a href="{{ product.get_absolute_url }}">
							<div class="background_img_thumb" style="height: 160px;"></div>
						</a>
					{% endif %}
				</td>
				<td>
					<h3 style="margin-top: 0px;"><a class="text" href="{{ product.get_absolute_url }}">{{ product }}</a></h3>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>

{% endblock content %}

templates/products/single.html
{% extends 'base.html' %}

{% block head_title %}
	- {{ product.title }}
{% endblock %}

	<div class="page-header">
		<h1>{{ product.title }}</h1>
	</div>

{% block content %}
	<div class="row">
		<div class="col-sm-4">
			{% for img in images %}
				{% if img.featured %}
					<div class="col-xs-12">
						<img class="img-responsive" src="{{ MEDIA_URL }}{{ img.image }}" />
					<hr/>
					</div>
				{% endif %}
			{% endfor %}
			{% for img in images %}
				{% if not img.featured %}
					<div class="col-xs-6">
						<a href="#" class="thumbnail">
							<img dclass="img-responsive" src="{{ MEDIA_URL }}{{ img.image }}" />
						</a>
					</div>
				{% endif %}
			{% endfor %}
		</div>
		<div class="col-sm-8">
			<div class="col-sm-8 pull-left">
				<h1>{{ product.title }}</h1>
			</div>
			<div class="col-sm-4 pull-right">
				<form class="form pull-right" method="POST" action="{% url 'add_to_cart' product.slug %}"> {% csrf_token %}
					<input class="btn btn-warning btn-block" type="submit" value="Add to Cart" />
					<!-- <input class="form-control" name="qty" type="number" value="1" /> -->
					{% if product.variation_set.all %}
						{% if product.variation_set.sizes %}
							<select class="form-control" name="size">
								{% for item in product.variation_set.sizes %}
									<option value="{{ item.title|lower }}">{{ item.title|capfirst }}</option>
								{% endfor %}
							</select>
						{% endif %}

						{% if product.variation_set.colors %}
							<select class="form-control" name="color">
								{% for item in product.variation_set.colors %}
									<option value="{{ item.title|lower }}">{{ item.title|capfirst }}</option>
								{% endfor %}
							</select>
						{% endif %}
					{% endif %}
				</form> 
			</div>
			<div class="col-sm-12">
				<hr/>
					{% if product.discount_price %}
						<h4 class="text">Price: ${{ product.discount_price }}</h4>
					{% else %}
						<h4 class="text">Price: ${{ product.price }}</h4>
					{% endif %}
				<hr/>
			</div>
			<div class="col-sm-12">
				{% if product.description %}
					<br/>{{ product.description|linebreaks }}
				{% endif %}
			</div>
		</div>
	</div>
{% endblock content %}